# variables used in the build
variables:
  checkout: 0.12.6
  packaging_tag: 0.12.6-1
  iteration: '1'
  pre_release: false
  draft: false

# package builds will always be manually triggered
trigger: none

jobs:
- job: 'msvc2015'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      win64:
        target: msvc2015-win64
  timeoutInMinutes: 0
  steps:
  - script: |
      choco install -yr --no-progress vcbuildtools -ia "/Full"
      pip install -q conan
      cmd /c attrib "C:\Program Files (x86)\Windows Kits\10\include\wdf" +H
    displayName: 'install dependencies'
  - script: |
      git clone --recurse-submodules https://github.com/wkhtmltopdf/wkhtmltopdf.git
      cd wkhtmltopdf && git checkout $(checkout) && git submodule update
    displayName: 'clone wkhtmltopdf'
  - script: python build vagrant $(target) --version - - --iteration $(iteration) wkhtmltopdf
    displayName: 'build package'
  - task: GithubRelease@0
    displayName: 'upload package'
    inputs:
      gitHubConnection: easonyq
      repositoryName: wkhtmltopdf/packaging
      action: edit
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '$(packaging_tag)'
      isDraft: '$(draft)'
      isPreRelease: '$(pre_release)'
      addChangeLog: false
      assetUploadMode: replace
      assets: |
        *.exe
